### ISSUE TITLE
Bro , it feels like ,trust me and run that .exe it is not a virus

### ISSUE THREAD

**Issue by Michael-Pio** [max9836/microsoft-rewards-automator#5]

**Comment by max9836** [comment]
Hi, 
I created this program in visual studio with .NET framework. It is fine if you don't trust this, but I really encourage you to do this, as you are interested in this. Also, this program aims to save everyone's time, not for spy to seek your privacy. So, again, if you don't trust this, it is definitely fine, just don't download it, and look for another program. But to my experience, this program is much more safer. Why? I am an **INDIVIDUAL** programmer, not a team, not a company. But if this doesn't satisfy you, I hope you may go look for another program, and find out which program is better.
Good luck,
Max
