### ISSUE TITLE
Are you sure this wont ban our accounts

### ISSUE THREAD

**Issue by helppleaseeee** [max9836/microsoft-rewards-automator#6]
i have been looking for rewards scripts in github and i found many of them, but unable to have the knowledge on how to use those script im suffering. this seems little easy for me to use, so please guide me.

**Comment by max9836** [comment]
Hi,
We are currently improving our program, aiming to reduce the amount of user account being banned by Microsoft Rewards. The new release will be publish on August. If you are new to Microsoft Rewards, you will not be banned. However, if you are unlucky (being banned), please

**Comment by max9836** [comment]
Fixed in v.7.9.0-improved
